# Generated by Django 3.1.4 on 2020-12-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201224_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='tags',
        ),
    ]
